version: "3.8"

services:
    maizeviz:
        command: nginx -g 'daemon off;'
        container_name: maizeviz
        image: maizeviz
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        ports:
            - "8080:8080"