name: Build
on: [push]

permissions:
  actions: read
  contents: read

jobs:
  buildPaper:
    environment: build
    runs-on: ubuntu-latest
    name: Build Paper
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Update apt
        run: sudo apt-get update
      - name: Install Pandoc
        run: sudo apt-get install pandoc pandoc-citeproc texlive-extra-utils texlive-fonts-recommended texlive-latex-base texlive-latex-extra texlive-bibtex-extra biber
      - name: Install zip
        run: sudo apt-get install zip
      - name: Install other deps
        run: cd paper; pip install -r requirements.txt
      - name: Build paper
        run: cd paper; bash render.sh
      - name: Move export
        run: mv paper/arxiv.zip arxiv.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: arxiv
          path: arxiv.zip
          if-no-files-found: error
  buildDeploy:
    environment: build
    runs-on: ubuntu-latest
    name: Build Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Build deploy
        run: bash prepare_viz_deploy.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: deploy
          path: deploy.zip
          if-no-files-found: error
      - name: Check build
        run: python paper/viz/script/check_deploy.py deploy
  deploy:
    environment: deploy
    name: Deploy
    runs-on: ubuntu-latest
    needs: [buildPaper, buildDeploy]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: deploy
      - name: Unzip
        run: unzip deploy.zip 
      - name: Deploy
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.SFTPHOST }}
          port: 22
          username: ${{ secrets.SFTPUSER }}
          password: ${{ secrets.SFTPPASSWORD }}
          localPath: './deploy'
          remotePath: './ag-adaptation-study.pub'