name: Build
on: [push]

permissions:
  actions: read
  contents: read

buildDeploy:
    environment: build
    runs-on: ubuntu-latest
    name: Build Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Build deploy
        run: prepare_deploy.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: deploy
          path: deploy.zip
          if-no-files-found: error
      - name: Check build
        run: bash script/check_deploy.sh
  deploy:
    environment: deploy
    name: Deploy
    runs-on: ubuntu-latest
    needs: [buildDeploy]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: deploy
      - name: Unzip
        run: unzip deploy.zip 
      - name: Deploy
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.SFTPHOST }}
          port: 22
          username: ${{ secrets.SFTPUSER }}
          password: ${{ secrets.SFTPPASSWORD }}
          localPath: './deploy'
          remotePath: './ag-adaptation-study.pub'